// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckEmail(ctx context.Context, email string) (string, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateCategory(ctx context.Context, category string) (Category, error)
	CreateCourseProgress(ctx context.Context, arg CreateCourseProgressParams) (CourseProgress, error)
	CreateCourses(ctx context.Context, arg CreateCoursesParams) (Course, error)
	CreateLessonCompletion(ctx context.Context, arg CreateLessonCompletionParams) (LessonCompletion, error)
	CreateMark(ctx context.Context, arg CreateMarkParams) (Mark, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateProfilePicture(ctx context.Context, arg CreateProfilePictureParams) (ProfilePicture, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserStatus(ctx context.Context, arg CreateUserStatusParams) (UserStatus, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteAssignment(ctx context.Context, assignmentID int64) error
	DeleteCategory(ctx context.Context, categoryID int64) error
	DeleteCourseProgress(ctx context.Context, courseprogressID int64) error
	DeleteCourses(ctx context.Context, courseID int64) error
	DeleteLessonCompletion(ctx context.Context, completionID int64) error
	DeleteMark(ctx context.Context, markID int64) error
	DeleteMaterial(ctx context.Context, materialID int64) error
	DeleteProfilePicture(ctx context.Context, userID int64) error
	DeleteSubmission(ctx context.Context, arg DeleteSubmissionParams) error
	DeleteUserStatus(ctx context.Context, statusID int64) error
	DeleteUsers(ctx context.Context, userID int64) error
	GetAssignment(ctx context.Context, assignmentID int64) (Assignment, error)
	GetCategory(ctx context.Context, categoryID int64) (Category, error)
	GetCompletedLessonsCount(ctx context.Context, arg GetCompletedLessonsCountParams) (int64, error)
	GetCourseByUserID(ctx context.Context, userID int64) (Course, error)
	GetCourseCompletedUserCount(ctx context.Context, progress int64) (int64, error)
	GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) (CourseProgress, error)
	GetCourses(ctx context.Context, courseID int64) (Course, error)
	GetEntireCourse(ctx context.Context, courseID int64) (GetEntireCourseRow, error)
	GetInProgressCourseCount(ctx context.Context) (int64, error)
	GetLessonCompletion(ctx context.Context, arg GetLessonCompletionParams) (LessonCompletion, error)
	GetMark(ctx context.Context, markID int64) (Mark, error)
	GetMaterial(ctx context.Context, arg GetMaterialParams) (Material, error)
	GetMaterialByOrderNumber(ctx context.Context, arg GetMaterialByOrderNumberParams) (Material, error)
	GetProfilePicture(ctx context.Context, userID int64) (ProfilePicture, error)
	GetRequest(ctx context.Context, requestID int64) (Request, error)
	GetSession(ctx context.Context, sessionID pgtype.UUID) (Session, error)
	GetStudentCountInCourse(ctx context.Context) ([]int64, error)
	GetSubmission(ctx context.Context, arg GetSubmissionParams) (Submission, error)
	GetSubscription(ctx context.Context, userID int64) (Subscription, error)
	GetSubscriptionByUser(ctx context.Context, arg GetSubscriptionByUserParams) (GetSubscriptionByUserRow, error)
	GetTotalCourseCount(ctx context.Context) (int64, error)
	GetTotalMaterialsInCourse(ctx context.Context, courseID int64) (int64, error)
	GetTotalRegisteredUserCount(ctx context.Context, isEmailVerified bool) (int64, error)
	GetTotalSubscribedUserCount(ctx context.Context, active bool) (int64, error)
	GetTotalUserCompletedCourseCount(ctx context.Context, arg GetTotalUserCompletedCourseCountParams) (int64, error)
	GetTotalUserCount(ctx context.Context, role string) (int64, error)
	GetUser(ctx context.Context, userName string) (User, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	GetUserCountForCertianCourse(ctx context.Context, arg GetUserCountForCertianCourseParams) (int64, error)
	GetUserStatus(ctx context.Context, userID int64) (UserStatus, error)
	GetsubmissionsByAssignment(ctx context.Context, assignmentID int64) (Submission, error)
	GetsubmissionsByUser(ctx context.Context, userID int64) (Submission, error)
	ListAllCategories(ctx context.Context, arg ListAllCategoriesParams) ([]Category, error)
	ListAllCourseByCatagory(ctx context.Context, catagory string) ([]ListAllCourseByCatagoryRow, error)
	ListAllCourseCatagories(ctx context.Context) ([]string, error)
	ListCourseProgressByUser(ctx context.Context, arg ListCourseProgressByUserParams) ([]CourseProgress, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListMarks(ctx context.Context, arg ListMarksParams) ([]Mark, error)
	ListMaterial(ctx context.Context, courseID int64) ([]ListMaterialRow, error)
	ListMaterialByCourse(ctx context.Context, courseID int64) ([]Material, error)
	ListSubscriptionsByCourse(ctx context.Context, arg ListSubscriptionsByCourseParams) ([]Subscription, error)
	ListSubscriptionsByUser(ctx context.Context, arg ListSubscriptionsByUserParams) ([]Subscription, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	ListUserStatus(ctx context.Context, arg ListUserStatusParams) ([]UserStatus, error)
	Listsubmissions(ctx context.Context, arg ListsubmissionsParams) ([]Submission, error)
	StudentCount(ctx context.Context, role string) (int64, error)
	UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCourseProgress(ctx context.Context, arg UpdateCourseProgressParams) (CourseProgress, error)
	UpdateCourses(ctx context.Context, arg UpdateCoursesParams) (Course, error)
	UpdateLessonCompletion(ctx context.Context, arg UpdateLessonCompletionParams) (LessonCompletion, error)
	UpdateMark(ctx context.Context, arg UpdateMarkParams) (Mark, error)
	UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error)
	UpdateProfilePicture(ctx context.Context, arg UpdateProfilePictureParams) (ProfilePicture, error)
	UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error)
	UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (Submission, error)
	UpdateSubscriptions(ctx context.Context, arg UpdateSubscriptionsParams) (Subscription, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UserStatus, error)
	UpdateUserStatusByAdmin(ctx context.Context, arg UpdateUserStatusByAdminParams) (UserStatus, error)
	UpdateUsersPassword(ctx context.Context, arg UpdateUsersPasswordParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
